

def opTitle():
    print ""
    print ""
    print ""
    print "          QQQQQQQQQ                    AAA               "
    print "        QQ:::::::::QQ                 A:::A              "
    print "      QQ:::::::::::::QQ              A:::::A             "
    print "     Q:::::::QQQ:::::::Q            A:::::::A            "
    print "     Q::::::O   Q::::::Q           A:::::::::A           "
    print "     Q:::::O     Q:::::Q          A:::::A:::::A          "
    print "     Q:::::O     Q:::::Q         A:::::A A:::::A         "
    print "     Q:::::O     Q:::::Q        A:::::A   A:::::A        "
    print "     Q:::::O     Q:::::Q       A:::::A     A:::::A       "
    print "     Q:::::O     Q:::::Q      A:::::AAAAAAAAA:::::A      "
    print "     Q:::::O  QQQQ:::::Q     A:::::::::::::::::::::A     "
    print "     Q::::::O Q::::::::Q    A:::::AAAAAAAAAAAAA:::::A    "
    print "     Q:::::::QQ::::::::Q   A:::::A             A:::::A   "
    print "      QQ::::::::::::::Q   A:::::A               A:::::A  "
    print "        QQ:::::::::::Q   A:::::A                 A:::::A "
    print "          QQQQQQQQ::::QQAAAAAAA                   AAAAAAA"
    print "                  Q:::::Q                                "
    print "                   QQQQQQ"
    print ""
    print ""
    print ""
    print ""
    print ""
    print "     .oPYo.                       o                   .oPYo. 8               .oPYo.          o  "
    print "     8                                                8    8 8               8    8          8  "
    print "     `Yooo. .oPYo. .oPYo. .oPYo. o8 .oPYo. odYo.     o8YooP' 8 .oPYo. o    o 8    8 o    o  o8P "
    print "         `8 8oooo8 Yb..   Yb..    8 8    8 8' `8      8      8 .oooo8 8    8 8    8 8    8   8  "
    print "          8 8.       'Yb.   'Yb.  8 8    8 8   8      8      8 8    8 8    8 8    8 8    8   8  "
    print "     `YooP' `Yooo' `YooP' `YooP'  8 `YooP' 8   8      8      8 `YooP8 `YooP8 `YooP' `YooP'   8  "
    print "                                                                         8 "
    print "                                                                      ooP'"
    print ""
    print ""
    print ""
    
